### ISSUE TITLE
Editor page goes blank

### ISSUE THREAD

**Issue by ericdatakelly** [Quansight/conda-store#458] opened 2023-04-11 21:01 UTC
When attempting to edit an existing environment, either in my namespace or global, about a second after clicking the edit button, the page goes blank.  There is no error message, just a white empty web page.  If I reload the page, I'm taken back to the conda-store UI with no environments selected.

https://user-images.githubusercontent.com/24855669/231287166-ce7c44a5-a3cc-4fc3-bb3d-eb8e500be4e1.mov

**Comment by costrouc** [comment] 2023-04-12 20:18
Thanks for the issue @ericdatakelly and a great video to reproduce the issue. I'll make sure that this issue is cross posted in https://github.com/quansight/conda-store-ui since this is ultimately where this needs to be solved.

**Comment by iameskild** [comment] 2023-04-13 16:10
@ericdatakelly @costrouc I was able to capture some logs for this issue. I've run into this a few times this morning but it does seem intermittent...

[nebari.quansight.dev-1681402032943.log](https://github.com/Quansight/conda-store/files/11224166/nebari.quansight.dev-1681402032943.log)

**Comment by ericdatakelly** [comment] 2023-04-13 18:30
Several times this morning, it happened on a large env but not a small environment.  I tried several times going back and forth between the large and small envs and only the large env experienced the blank page.

**Comment by trallard** [comment] 2023-07-21 16:05
This seems to have been resolved by #240

**Closed by trallard** 2023-07-21 16:05 UTC
Labels: type: bug 🐛
